/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnowView: typeof import('./src/components/SnowView.vue')['default']
  }
}

// For TSX support
declare global {
  const FooterView: typeof import('./src/components/FooterView.vue')['default']
  const HeaderView: typeof import('./src/components/HeaderView.vue')['default']
  const MapView: typeof import('./src/components/MapView.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SnowView: typeof import('./src/components/SnowView.vue')['default']
}