/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/article/[:id]': RouteRecordInfo<
      '/article/[:id]',
      '/article/::id',
      { :id: ParamValue<true> },
      { :id: ParamValue<false> },
      | never
    >,
    '/chat/': RouteRecordInfo<
      '/chat/',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/': RouteRecordInfo<
      '/community/',
      '/community',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/[:id]': RouteRecordInfo<
      '/community/[:id]',
      '/community/::id',
      { :id: ParamValue<true> },
      { :id: ParamValue<false> },
      | never
    >,
    '/crowd/': RouteRecordInfo<
      '/crowd/',
      '/crowd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/device/': RouteRecordInfo<
      '/device/',
      '/device',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/secret/': RouteRecordInfo<
      '/secret/',
      '/secret',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sport/': RouteRecordInfo<
      '/sport/',
      '/sport',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sport/[:id]': RouteRecordInfo<
      '/sport/[:id]',
      '/sport/::id',
      { :id: ParamValue<true> },
      { :id: ParamValue<false> },
      | never
    >,
    '/trash/': RouteRecordInfo<
      '/trash/',
      '/trash',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/': RouteRecordInfo<
      '/user/',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/article/[:id].vue': {
      routes:
        | '/article/[:id]'
      views:
        | never
    }
    'src/pages/chat/index.vue': {
      routes:
        | '/chat/'
      views:
        | never
    }
    'src/pages/community/index.vue': {
      routes:
        | '/community/'
      views:
        | never
    }
    'src/pages/community/[:id].vue': {
      routes:
        | '/community/[:id]'
      views:
        | never
    }
    'src/pages/crowd/index.vue': {
      routes:
        | '/crowd/'
      views:
        | never
    }
    'src/pages/device/index.vue': {
      routes:
        | '/device/'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/secret/index.vue': {
      routes:
        | '/secret/'
      views:
        | never
    }
    'src/pages/sport/index.vue': {
      routes:
        | '/sport/'
      views:
        | never
    }
    'src/pages/sport/[:id].vue': {
      routes:
        | '/sport/[:id]'
      views:
        | never
    }
    'src/pages/trash/index.vue': {
      routes:
        | '/trash/'
      views:
        | never
    }
    'src/pages/user/index.vue': {
      routes:
        | '/user/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
